# activation de modsecurity
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On

#  hardened configuration
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject
SecRequestBodyInMemoryLimit 131072

SecResponseBodyLimit 524288
SecResponseBodyLimitAction ProcessPartial
SecResponseBodyMimeType text/plain text/html text/xml application/json

SecTmpDir /tmp/transcendence-waf/
SecDataDir /var/lib/transcendence-waf/

# logging production
SecDebugLog /var/log/transcendence-waf/debug.log
SecDebugLogLevel 0
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^[45]"
SecAuditLogParts ABDEFHIJZ
SecAuditLogType Serial
SecAuditLog /var/log/transcendence-waf/audit.log
SecErrorLog /var/log/transcendence-waf/error.log

# masquage serveur
SecServerSignature "Transcendence-WAF"
SecArgumentSeparator &

# types de contenu supportés
SecRule REQUEST_HEADERS:Content-Type "^application/x-www-form-urlencoded" \
    "id:200001,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=URLENCODED"

SecRule REQUEST_HEADERS:Content-Type "^multipart/form-data" \
    "id:200002,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=MULTIPART"

SecRule REQUEST_HEADERS:Content-Type "^text/xml" \
    "id:200003,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"

SecRule REQUEST_HEADERS:Content-Type "^application/xml" \
    "id:200004,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"

SecRule REQUEST_HEADERS:Content-Type "^application/json" \
    "id:200005,phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"

# include des règles de sécurité
Include /etc/modsecurity/rules/coreruleset/*.conf
Include /etc/transcendence-waf/rules/*.conf
# pas encore configuré les regles
